// PM2 ecosystem manifest for Full 8-Cell Benchmark Matrix (4 Strategies x 2 Decision Modes)

module.exports = {
  apps: [
    // Sniper
    {
      name: 'charon-sniper-llm',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/sniper-llm.out.log',
      error_file: './logs/sniper-llm.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/sniper_llm.sqlite',
        ACTIVE_STRATEGY_ID: 'sniper',
        FORCE_USE_LLM: 'true',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },
    {
      name: 'charon-sniper-rules',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/sniper-rules.out.log',
      error_file: './logs/sniper-rules.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/sniper_rules.sqlite',
        ACTIVE_STRATEGY_ID: 'sniper',
        FORCE_USE_LLM: 'false',
        DISABLE_TELEGRAM_POLLING: 'true',
        ENABLE_FORWARD_RESOLVER: 'true',
      },
    },

    // Dip Buy
    {
      name: 'charon-dip_buy-llm',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/dip_buy-llm.out.log',
      error_file: './logs/dip_buy-llm.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/dip_buy_llm.sqlite',
        ACTIVE_STRATEGY_ID: 'dip_buy',
        FORCE_USE_LLM: 'true',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },
    {
      name: 'charon-dip_buy-rules',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/dip_buy-rules.out.log',
      error_file: './logs/dip_buy-rules.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/dip_buy_rules.sqlite',
        ACTIVE_STRATEGY_ID: 'dip_buy',
        FORCE_USE_LLM: 'false',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },

    // Smart Money
    {
      name: 'charon-smart_money-llm',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/smart_money-llm.out.log',
      error_file: './logs/smart_money-llm.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/smart_money_llm.sqlite',
        ACTIVE_STRATEGY_ID: 'smart_money',
        FORCE_USE_LLM: 'true',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },
    {
      name: 'charon-smart_money-rules',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/smart_money-rules.out.log',
      error_file: './logs/smart_money-rules.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/smart_money_rules.sqlite',
        ACTIVE_STRATEGY_ID: 'smart_money',
        FORCE_USE_LLM: 'false',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },

    // Degen
    {
      name: 'charon-degen-llm',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/degen-llm.out.log',
      error_file: './logs/degen-llm.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/degen_llm.sqlite',
        ACTIVE_STRATEGY_ID: 'degen',
        FORCE_USE_LLM: 'true',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },
    {
      name: 'charon-degen-rules',
      script: 'index.js',
      cwd: __dirname,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '30s',
      restart_delay: 3000,
      watch: false,
      out_file: './logs/degen-rules.out.log',
      error_file: './logs/degen-rules.err.log',
      merge_logs: true,
      time: true,
      env: {
        DB_PATH: './data/degen_rules.sqlite',
        ACTIVE_STRATEGY_ID: 'degen',
        FORCE_USE_LLM: 'false',
        DISABLE_TELEGRAM_POLLING: 'true',
      },
    },
  ],
};
